config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/test_callback', to: 'documents#test_callback'

  get '/sign-up', to: 'sessions#sign_up', as: 'sign_up'
  post '/sign-up', to: 'sessions#sign_up'

  resource :session, only: [:create, :destroy] do
    collection do
      get :login

      get :okta_login
      post :okta_login

      post :renew_fennel_access_token
    end
  end

  resources :documents, only: [:index] do
    collection do
      post :cron_expression_description
    end
  end

  resources :users, only: [:update] do
    collection do
      get :profile
    end
  end

  resources :teams, only: [] do
    member do
      get :members
      post :members

      post :toggle_team_leader
      delete :remove_member
    end
    resources :pokes
  end

  resources :pokes, only: [:index, :create]

  get 'under_grounds', to: 'under_grounds#teams'
  resources :under_grounds, only: [] do
    collection do
      get :teams
      get :application_admins
      get :miscellaneous
      get :statistics

      post :teams
      post :application_admins
      post :miscellaneous
      post :statistics

      delete :application_admins
    end
  end

  resources :enumerations, only: [], constraints: lambda {|req| req.format == :json} do
    collection do
      get :people
    end
  end

  # Defines the root path route ("/")
  root to: 'sessions#index'
end

app/controllers/under_grounds_controller.rb
class UnderGroundsController < ApplicationController

  # --------- Module inclusions --------------------------------------------
  include ActionView::Helpers::TextHelper

  # --------- Filters ------------------------------------------------------
  before_action :restricted_to_application_admin_only

  # --------- Actions ------------------------------------------------------
  def teams
    return if request.method == 'GET'

    @team = Team.where(id: params[:team_id]).take

    flash.now[:notice] = @flash_notice = if @team
                                           if params[:action_2_perform] == 'update'
                                             if (@result = @team.update(team_params))
                                               "Team updated successfully."
                                             else
                                               "Update failed because of #{@team.errors.full_messages.to_sentence}"
                                             end
                                           elsif params[:action_2_perform] == 'delete'
                                             if (@result = @team.destroy)
                                               "Team removed."
                                             else
                                               "Failed to delete because of #{@team.errors.full_messages.to_sentence}"
                                             end
                                           else
                                             'Invalid action to perform.'
                                           end
                                         elsif params[:action_2_perform] == 'add'
                                           _team_leaders = (params[:fmnos_with_name_and_email] || []).uniq.collect do |fmno_with_name_and_email|
                                             _matched_data = fmno_with_name_and_email.match(/(.+) \(name: (.*)\) \(email: (.*)\)\z/i)

                                             member = User.find_or_initialize_by(fmno: _matched_data[1])

                                             if member.new_record?
                                               member.name = (_matched_data[2].present? ? _matched_data[2] : nil)
                                               member.email = (_matched_data[3].present? ? _matched_data[3] : nil)
                                             end

                                             member
                                           end

                                           _team = Team.new(team_params)

                                           if (@result = _team.save)
                                             _team.team_leaders = _team_leaders
                                             "Team: '#{_team.name}' created successfully."
                                           else
                                             "Failed to create team because, #{_team.errors.full_messages.to_sentence}."
                                           end
                                         else
                                           'Team not found.'
                                         end
  end

  def application_admins
    if request.xhr?

      flash[:notice] = if params[:action_2_perform] == 'add'
                         _members = (params[:fmnos_with_name_and_email] || []).uniq.collect do |fmno_with_name_and_email|
                           _matched_data = fmno_with_name_and_email.match(/(.+) \(name: (.*)\) \(email: (.*)\)\z/i)

                           member = User.find_or_initialize_by(fmno: _matched_data[1])

                           if member.new_record?
                             member.name = (_matched_data[2].present? ? _matched_data[2] : nil)
                             member.email = (_matched_data[3].present? ? _matched_data[3] : nil)
                           end

                           member.application_admin = true

                           member
                         end

                         success_count = 0
                         failed_count = 0

                         _members.each do |member|
                           if member.save
                             success_count += 1
                           else
                             Rails.logger.debug(member.errors.inspect)
                             failed_count += 1
                           end
                         end

                         messages = []
                         messages << "Successfully added #{pluralize(success_count, 'application admin')}"
                         messages << "while #{failed_count} failed" if failed_count > 0

                         messages.join(' ')
                       elsif params[:action_2_perform] == 'remove'
                         if (user = User.application_admins.where(id: params[:user_id]).take)
                           if user.update(application_admin: false)
                             'Application admin removed.'
                           else
                             Rails.logger.debug(user.errors.inspect)
                             "Failed to remove application admin because, #{user.errors.full_messages.to_sentence}."
                           end
                         else
                           'Application admin not found.'
                         end
                       else
                         'Invalid action to perform.'
                       end
    end
  end

  def miscellaneous
    if request.xhr?

      _notice = if params[:action_2_perform] == "toggle_signup"

                  if Rails.cache.exist?(LABEL_SIGNUP_ENABLED)
                    Rails.cache.delete(LABEL_SIGNUP_ENABLED)
                    "Sign up switched off."
                  else
                    Rails.cache.write(LABEL_SIGNUP_ENABLED, Time.now, expires_in: 10.minutes)
                    "Sign up switched on for next 10 mins."
                  end

                 else
                  "Invalid action to perform"
                end

      flash.now[:notice] = _notice if _notice
    end
  end

  def statistics
    return if request.get?

    flash.now[:notice] = if params[:action_2_perform] == 'flush_and_reap_idle_connections'
                           ActiveRecord::Base.connection_pool.flush
                           ActiveRecord::Base.connection_pool.reap

                           "Idle database connections flushed and reaped."
                         else
                           'Invalid action to perform.'
                         end
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end

  def restricted_to_application_admin_only
    unless Current.user.application_admin?
      _message = "Access restricted. Only application's admin are passed through."

      if request.xhr?
        flash[:notice] = _message
        render js: "window.location = '#{root_url}'"
      else
        redirect_to(root_path, notice: _message)
      end
    end
  end

end

app/views/under_grounds/_application_admins_tab_content.html.erb
<h5>Application admins</h5>

<div class="row">

  <!-- New application admin form-->
  <div class="col-12 mb-4">
    <div class="card">
      <div class="card-body">

        <div class="row edit_card">
          <div class="col-12">
            <h5>Add new</h5>
            <%= form_with url: application_admins_under_grounds_path(action_2_perform: :add), method: :post, local: false do %>

              <div class="row mb-3">
                <div class="col-12">
                  <%= select_tag 'fmnos_with_name_and_email[]', '', multiple: true, id: 'fmnos_select2_field', class: 'form-control' %>
                </div>
              </div>
              <div class="row">
                <div class="col-12 text-right">
                  <%= submit_tag 'Add Application admins', class: "btn btn-sm btn-primary" %>
                </div>
              </div>
            <% end %>

            <script type="text/javascript">
                $('#fmnos_select2_field').select2({
                    theme: "bootstrap",
                    placeholder: "Search and select users(members) by name or fmno to add as 'Application admin'",
                    multiple: true,
                    ajax: {
                        url: '<%=people_enumerations_path(format: :json, combine_name_email_and_fmno: true) %>',
                        dataType: 'json'
                    }
                });
            </script>

          </div>
        </div>

      </div>
    </div>
  </div>

  <% User.application_admins.each do |user| %>
    <%= render(partial: 'under_grounds/user_card', locals: {user: user}) %>
  <% end %>
</div>

app/views/under_grounds/_current_crontab_view.html.erb
<div class="row mb-3 current_crotab_view">
  <div class="col">
    <div class="card border-info">
      <div class="card-body">
        <h5 class="card-title">Current Crontab view</h5>

        <div class="card-text">
          <pre><%= File.exist?('carom-crontab') ? File.read('carom-crontab') : 'Cron tab file not available!' %></pre>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/under_grounds/_database_connection_pool_statistics_content.html.erb
<div class="row mb-5" id="db_connection_pool_statistics_content">
  <div class="col">
    <h5>Database connection pool statistics</h5>

    <div class="card border-info">
      <div class="card-body">
        <div class="card-text">
          <h5><%= ActiveRecord::Base.connection_db_config.configuration_hash.dig(:host) %></h5>
          <table class="table table-sm table-striped ">
            <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Attribute name</th>
              <th scope="col">Attribute value</th>
            </tr>
            </thead>
            <tbody>

            <% ActiveRecord::Base.connection_pool.stat.each_with_index do |attribute, index| %>
              <tr>
                <th scope="row"><%= (index + 1).to_s.rjust(3, '0') %></th>
                <td><%= attribute[0] %></td>
                <td><%= attribute[1] %></td>
              </tr>
            <% end %>
            </tbody>
          </table>

          <%= button_to "Flush & Reap idle connections", statistics_under_grounds_path(action_2_perform: 'flush_and_reap_idle_connections'),
                        remote: true, data: {confirm: 'Are you sure?'}, class: "btn btn-sm btn-outline-primary" %>

        </div>

      </div>
    </div>

  </div>
</div>

app/views/under_grounds/_menu_bar.html.erb
<%
  ug_menu_items = []
  ug_menu_items << {label: 'Teams', url: teams_under_grounds_path, match: {controller: 'under_grounds', action: 'teams'}}
  ug_menu_items << {label: 'Application admins', url: application_admins_under_grounds_path, match: {controller: 'under_grounds', action: 'application_admins'}}
  ug_menu_items << {label: 'Statistics', url: statistics_under_grounds_path, match: {controller: 'under_grounds', actions: ['statistics']}}
  ug_menu_items << {label: 'Miscellaneous', url: miscellaneous_under_grounds_path, match: {controller: 'under_grounds', action: 'miscellaneous'}}
%>
<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
  <% ug_menu_items.each do |ug_menu_items| %>
    <%= link_to ug_menu_items[:label], ug_menu_items[:url], class: "nav-link shadow-sm mb-2 #{'active' if ug_menu_items[:match] == {controller: params[:controller], action: params[:action]}}" %>
  <% end %>
</div>

app/views/under_grounds/_statistics_tab_content.html.erb
<%= render(partial: 'under_grounds/database_connection_pool_statistics_content') %>

app/views/under_grounds/_tab_structure.html.erb
<div class="row">
  <div class="col-12"><h4>Under ground</h4>
    <hr/>
  </div>
</div>

<div class="row">
  <div class="col-9">
    <div class="tab-content">
      <div class="tab-pane fade show active">
        <%= render(partial: partial_to_render) %>
      </div>
    </div>
  </div>
  <div class="col-3">
    <%= render(partial: 'under_grounds/menu_bar') %>
  </div>
</div>

app/views/under_grounds/_team_card.html.erb
<% dom_id = "team_card_#{team.id}" %>
<div id='<%= dom_id %>' class="col-12 mb-4">
  <div class="card">
    <div class="card-body">
      <div class="row view_card">
        <div class="col-12">
          <h5><%= team.name %> (id: <%= team.id %>)</h5>
        </div>
        <div class="col-12">
          <div class="row border-bottom">
            <div class="col-3 text-right">Team leaders:</div>
            <div class="col-9">
              <% team.team_leaders.each do |member| %>
                <li><%= member.email_with_name %></li>
              <% end %>
            </div>
          </div>
          <div class="row border-bottom">
            <div class="col-3 text-right">Team members:</div>
            <div class="col-9">
              <% team.team_members.each do |member| %>
                <li><%= member.email_with_name %></li>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-12 text-right">
          <%= link_to('Delete', teams_under_grounds_path(team_id: team, action_2_perform: :delete), method: :post,
                      remote: true, data: {confirm: 'Are you sure?'}, class: "btn btn-sm btn-outline-danger") %>
          <%= link_to('Edit', 'javascipt:void(0);', class: "btn btn-sm btn-outline-primary show_edit_card") %>
        </div>
      </div>
      <div class="row edit_card" style="display: none">
        <div class="col-12">
          <h5><%= team.name %> (id: <%= team.id %>)</h5>
          <%= form_with url: teams_under_grounds_path(team_id: team, action_2_perform: :update), method: :post, local: false, model: team do |f| %>
            <div class="row mb-3">
              <div class="col-6">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
            <div class="row">
              <div class="col-12 text-right">
                <%= link_to('Back', 'javascipt:void(0);', class: "btn btn-sm btn-outline-primary show_view_card") %>
                <%= f.submit nil, class: "btn btn-sm btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <script type="text/javascript">
          $('#<%= dom_id %> .show_edit_card').on('click', function () {
              $('#<%= dom_id %> .view_card').hide();
              $('#<%= dom_id %> .edit_card').show();
          });
          $('#<%= dom_id %> .show_view_card').on('click', function () {
              $('#<%= dom_id %> .edit_card').hide();
              $('#<%= dom_id %> .view_card').show();
          });
      </script>
    </div>
  </div>
</div>

app/views/under_grounds/_user_card.html.erb
<div class="col-sm-6 mb-4" id='user_card_<%= user.id %>'>
  <div class="card border-secondary">
    <div class="card-body">
      <div class="card-title">
        <div class="row">
          <div class="col-12">
            <h5><%= user.name %></h5>
          </div>
        </div>
      </div>

      <p class="card-text">
        Email: <%= user.email %><br/>
        Fmno: <%= user.fmno %>
      </p>

      <div class="btn-group btn-group-sm" role="group">
        <%= link_to("Remove", application_admins_under_grounds_path(action_2_perform: :remove, user_id: user.id),
                    method: :delete, class: "btn btn-outline-secondary", remote: true, data: {confirm: 'Are you sure?'}) %>
      </div>
    </div>
  </div>
</div>

app/views/under_grounds/application_admins.html.erb
<%= render(partial: 'under_grounds/tab_structure', locals: {partial_to_render: 'under_grounds/application_admins_tab_content'}) %>

app/views/under_grounds/miscellaneous.html.erb
<%= render(partial: 'under_grounds/tab_structure', locals: {partial_to_render: 'under_grounds/miscellaneous_tab_content'}) %>

app/views/under_grounds/miscellaneous.js.erb
$('.signup_toggle_form').replaceWith('<%=j(render(partial: 'under_grounds/signup_toggle_form')) %>');

$('.flash_notice_container').replaceWith('<%=j(render(partial: 'tool_components/flash_notice')) %>');

app/views/under_grounds/statistics.js.erb
$('#db_connection_pool_statistics_content').replaceWith('<%=j(render(partial: 'under_grounds/database_connection_pool_statistics_content')) %>');

$('.flash_notice_container').replaceWith('<%=j(render(partial: 'tool_components/flash_notice')) %>');

app/views/under_grounds/teams.html.erb
<%= render(partial: 'under_grounds/tab_structure', locals: {partial_to_render: 'under_grounds/team_tab_content'}) %>

app/views/under_grounds/teams.js.erb
<%if @team %>
  <%if params[:action_2_perform] == 'update' %>
    <%if @result %>
      $('#team_card_<%= @team.id %>').replaceWith('<%=j(render(partial: 'under_grounds/team_card', locals: {team: @team})) %>');
    <%end %>
  <%elsif params[:action_2_perform] == 'delete' %>
    <%if @result %>
      <%flash[:notice] = @flash_notice if @flash_notice %>
      window.location = '<%=teams_under_grounds_path %>';
    <%end %>
  <%end %>
<%elsif params[:action_2_perform] == 'add' %>
  <%if @result %>
    <%flash[:notice] = @flash_notice if @flash_notice %>
    window.location = '<%=teams_under_grounds_path %>';
  <%end %>
<%else %>
  alert("Unable to find the team.")
<%end %>

$('.flash_notice_container').replaceWith('<%=j(render(partial: 'tool_components/flash_notice')) %>');