config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/test_callback', to: 'documents#test_callback'

  get '/sign-up', to: 'sessions#sign_up', as: 'sign_up'
  post '/sign-up', to: 'sessions#sign_up'

  resource :session, only: [:create, :destroy] do
    collection do
      get :login

      get :okta_login
      post :okta_login

      post :renew_fennel_access_token
    end
  end

  resources :documents, only: [:index] do
    collection do
      post :cron_expression_description
    end
  end

  resources :users, only: [:update] do
    collection do
      get :profile
    end
  end

  resources :teams, only: [] do
    member do
      get :members
      post :members

      post :toggle_team_leader
      delete :remove_member
    end
    resources :pokes
  end

  resources :pokes, only: [:index, :create]

  get 'under_grounds', to: 'under_grounds#teams'
  resources :under_grounds, only: [] do
    collection do
      get :teams
      get :application_admins
      get :miscellaneous
      get :statistics

      post :teams
      post :application_admins
      post :miscellaneous
      post :statistics

      delete :application_admins
    end
  end

  resources :enumerations, only: [], constraints: lambda {|req| req.format == :json} do
    collection do
      get :people
    end
  end

  # Defines the root path route ("/")
  root to: 'sessions#index'
end

app/models/poke.rb
class Poke < ApplicationRecord

  # --------- Constants ----------------------------------------------------
  # For cron expression refer: https://www.freeformatter.com/cron-expression-generator-quartz.html
  CRON_HELP = <<EOF
Field name     Mandatory?   Allowed values    Allowed special characters
----------     ----------   --------------    --------------------------
Seconds        No           0-59              * / , -
Minutes        Yes          0-59              * / , -
Hours          Yes          0-23              * / , -
Day of month   Yes          1-31              * / , - L W
Month          Yes          1-12 or JAN-DEC   * / , -
Day of week    Yes          0-6 or SUN-SAT    * / , - L #
Year           No           1970–2099         * / , -
EOF

  CRON_FIELDS = {cron_seconds: '0', cron_minutes: '*', cron_hours: '*', cron_day_of_month: '*', cron_month: '*', cron_day_of_week: '*', cron_year: '*'}
  RESPONSE = 'RESPONSE'
  EXCEPTION = 'EXCEPTION'
  INACTIVE = 'inactive'

  # --------- Stored attributes --------------------------------------------
  store :other_attributes,
        accessors: ([:url, :validating_uuid, :latest_responses] + CRON_FIELDS.keys),
        coder: JSON

  # --------- Associations -------------------------------------------------
  belongs_to :team, inverse_of: :pokes

  # --------- Validations --------------------------------------------------
  validates :frequency, presence: true
  validates :url, presence: true,
            format: {with: /\Ahttps?:\/\/(.*\.intranet\.mckinsey\.com|[\w]{1,}|\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})(:\d+)?(\S*)\z/i,
                     message: 'should be valid McKinsey intranet(or host or ip address with/out port) url starting with http/https.'}
  validates :validating_uuid, presence: true

  # --------- Callbacks ----------------------------------------------------
  after_initialize do
    self.latest_responses ||= []
    CRON_FIELDS.each do |field_name, default_value|
      self.send("#{field_name}=", default_value) if self.send("#{field_name}").blank?
    end
  end

  before_validation :try_populating_cron_fields
  before_validation :try_populating_frequency
  before_validation :try_populating_validating_uuid
  before_validation :try_trimming_latest_responses

  before_save :allow_for_team_leaders_only
  before_destroy :allow_for_team_leaders_only

  after_commit :refresh_crontab_file, on: [:create, :update, :destroy]

  def refresh_crontab_file
    `rake carom:provision_cron`
  end

  # --------- Instance methods ---------------------------------------------
  def do(force = false, manual_call = false)
    if force or doable?
      Rails.logger.debug("Executing poke: #{['id', 'live', 'url', 'validating_uuid'].collect {|_method| {_method => self.send(_method)}}.inject(&:merge)}}")
      begin
        _response = Faraday.new(url: self.url, headers: {'user-agent': "Carom (Faraday gem -v #{`gem -v faraday`.try(:chomp)})",
                                                         'content-type': 'application/json',
                                                         'http-referrer': 'Carom poke',
                                                         'Validating-Uuid': self.validating_uuid}).post do |req|
          # req.body = params.to_json
        end

        (self.latest_responses ||= []).prepend([Time.now, RESPONSE, _response.headers["validating-uuid"], _response.status, _response.body])
      rescue Exception => e
        (self.latest_responses ||= []).prepend([Time.now, EXCEPTION, e.message, e.backtrace])
      end

      try_trimming_latest_responses(25)

      self.update_columns(other_attributes: self.other_attributes)

      unless doable?
        NotificationMailer.notify_team_members_for_inactive_poke(self).deliver_later if self.live and (not manual_call)
        self.update_columns(live: false)
      end
    end
  end

  def doable?
    return true if (self.latest_responses.blank? or
        (self.latest_responses.dig(0, 1) == RESPONSE and
            self.latest_responses.dig(0, 2) == self.validating_uuid and
            self.latest_responses.dig(0, 3).to_s =~ /2[0-9]{2}/i))

    false
  end

  private

  def try_populating_frequency
    self.frequency = CRON_FIELDS.keys.collect {|_field| self.send(_field).to_s.strip}.join(" ")
  end

  def try_populating_cron_fields
    CRON_FIELDS.each do |field_name, default_value|
      self.send("#{field_name}=", default_value) if self.send("#{field_name}").blank?
    end
  end

  def try_populating_validating_uuid
    self.validating_uuid ||= SecureRandom.uuid
  end

  #Only persist last 20 responses
  def try_trimming_latest_responses(last_n_responses = 20)
    self.latest_responses = self.latest_responses[0...last_n_responses]
  end

  def allow_for_team_leaders_only
    # return if Current.user and Current.user.leading_pokes.where(id: self.id).exists?
    # if _current_user = Current.user and _team = _current_user.teams.where(id: self.team_id).take and _team.team_leaders.include?(Current.user)
    # else
    return if Current.user and self.team.team_leaders.include?(Current.user)

    self.errors.add(:base, "not accessible for the operation. Only team leaders are allowed for create, update & delete operations.")
    throw(:abort)
  end

end

app/controllers/pokes_controller.rb
class PokesController < ApplicationController

  # --------- Filters ------------------------------------------------------
  before_action :fetch_leading_team, only: [:create]
  before_action :fetch_leading_poke, only: [:update, :destroy]

  def index
    @team = Current.user.teams.where(id: params[:team_id]).take
  end

  def create
    @poke = @team.pokes.new(poke_params)
    _notice = if @poke.save
                @poke.do(true, true)
                "Poke created successfully."
              else
                "Failed to create poke as #{@poke.errors.full_messages.to_sentence}"
              end

    flash[:notice] = flash.now[:notice] = _notice if _notice
  end

  def update
    _notice = if @poke.update(poke_params)
                @poke.do(true, true)
                "Poke updated successfully."
              else
                "Failed to update poke as #{@poke.errors.full_messages.to_sentence}"
              end

    flash.now[:notice] = _notice if _notice
  end

  def destroy
    _notice = if @poke.destroy
                "Poke deleted successfully."
              else
                "Failed to delete poke as #{@poke.errors.full_messages.to_sentence}"
              end

    flash.now[:notice] = _notice if _notice
  end

  private

  def poke_params
    params.require(:poke).permit(:live, :url, *Poke::CRON_FIELDS.keys)
  end

  def fetch_leading_team
    return if (@team = Current.user.leading_teams.where(id: params[:team_id]).take)
    redirect_on_inaccessible_team
  end

  def fetch_leading_poke
    return if (@poke = Current.user.leading_pokes.where(id: params[:id]).take)
    redirect_on_inaccessible_poke
  end

end

app/helpers/pokes_helper.rb
module PokesHelper
end

app/views/pokes/_card.html.erb
<div class="poke_form poke_form_<%= poke.id %>">

  <div class="alert alert-light border border-info" role="alert">
    <% if show_team_label ||= false %>
      <p>Team: <%= poke.team.name %></p>
    <% end %>

    <%= form_with(model: poke, url: team_poke_path(poke.team, poke), local: false, method: :delete, class: 'form mb-3') do |form| %>
      <div class="input-group input-group-sm">
        <div class="input-group-prepend">
          <span class="input-group-text"><strong><%= poke.id %></strong></span>
          <span class="input-group-text">Doable &nbsp; <i class="fa <%= poke.doable? ? 'fa-check' : 'fa-times' %>" aria-hidden="true"></i></span>
          <span class="input-group-text">Live &nbsp; <i class="fa <%= poke.live? ? 'fa-check' : 'fa-times' %>" aria-hidden="true"></i></span>
          <span class="input-group-text">Validating uuid</span>
        </div>
        <input type="text" class="form-control bg-transparent" value="<%= poke.validating_uuid %>" readonly="readonly">
        <div class="input-group-append">
          <a href="javascript:void(0);" class="btn btn-outline-info latest_response"><%= pluralize(poke.latest_responses.size, 'Response') %></a>
          <%= form.submit "Delete", class: "btn btn-outline-danger", data: {disable_with: 'Processing...', confirm: 'Are you sure?'} if poke.team.team_leaders.include?(Current.user) %>
        </div>
      </div>
    <% end %>

    <%= render(partial: 'pokes/form', locals: {poke: poke}) %>

    <div class="alert alert-info mb-0 monospace_text" style="display: none">
      <h6>Latest responses</h6>
      <% poke.latest_responses.each do |_response| %>
        <li><%= truncate(_response.inspect, length: 217) %></li>
      <% end %>
    </div>

  </div>

</div>

app/views/pokes/_form.html.erb
<%
  _url_to_post_to = if poke.new_record?
                      if poke.team
                        team_pokes_path(poke.team)
                      else
                        pokes_path
                      end
                    else
                      team_poke_path(poke.team, poke)
                    end
%>
<%= form_with(model: poke, url: _url_to_post_to, local: false, class: "form") do |form| %>

  <% unless poke.team %>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text" for="inputGroupSelect01">Team</label>
      </div>
      <%= select_tag :team_id, options_for_select(Current.user.leading_teams.collect {|team| [team.name, team.id]}), {prompt: 'Please select team from the following', class: "form-select form-control form-control-sm"} %>
    </div>
  <% end %>

  <div class="input-group input-group-sm">
    <div class="input-group-prepend">
      <span class="input-group-text">Cron expression</span>
    </div>
    <% Poke::CRON_FIELDS.keys.each do |_cron_field|
      _cron_field_label = _cron_field.to_s.gsub(/cron_/, '').humanize %>
      <%= form.text_field _cron_field, class: "form-control text-center cron_exp_field", placeholder: _cron_field_label, title: _cron_field_label %>
    <% end %>
  </div>
  <p class="text-right cron_exp_label mb-2">
    <small class="DDfont-weight-lighter"><%= Cronex::ExpressionDescriptor.new(poke.frequency).description unless poke.new_record? %></small>
  </p>

  <div class="input-group input-group-sm">
    <div class="input-group-prepend">
      <div class="input-group-text">
        <%= form.check_box :live, title: 'Check to make it live or uncheck otherwise.' %>
      </div>
    </div>
    <div class="input-group-prepend">
      <span class="input-group-text">URL to hit: </span>
    </div>
    <%= form.text_field :url, class: "form-control form-control-sm" %>
    <div class="input-group-append">
      <%= form.submit (poke.new_record? ? "Create" : "Update & Refresh"), class: "btn btn-primary", disabled: (not Current.user.leading_teams.exists?), data: {disable_with: 'Processing...'} %>
    </div>
  </div>
<% end %>

app/views/pokes/_new_card.html.erb
<div class="poke_form poke_form_<%= poke.id %>">

  <div class="alert alert-light border border-info" role="alert">
    <%= render(partial: 'pokes/form', locals: {poke: poke}) %>
  </div>

</div>

app/views/pokes/_pokes_tab_content.html.erb
<h5>Pokes</h5>

<div class="row">
  <div class="col-12">
    <div class="alert alert-info" style="font-size: 0.85rem" role="alert">
      <h6>Cron field valid values</h6>
      <hr/>
      <pre><%= Poke::CRON_HELP %></pre>
    </div>
  </div>
</div>

<%
  pokes = if @team
            @team.pokes
          else
            Current.user.accessible_pokes
          end
%>

<div class="row">
  <div class="col-12">

    <% if @team and @team.team_leaders.include?(Current.user) %>
      <%= render(partial: 'pokes/new_card', locals: {poke: @team.pokes.new}) %>
    <% elsif Current.user.leading_teams.exists? %>
      <%= render(partial: 'pokes/new_card', locals: {poke: Poke.new}) %>
    <% end %>

    <% if pokes.exists? %>
      <%= render(partial: 'pokes/card', collection: pokes.reload.order("id desc"), locals: {show_team_label: @team ? false : true}, as: :poke) %>
    <% else %>
      <div class="alert alert-primary" style="font-size: 0.85rem" role="alert">Existing pokes should appear here.</div>
    <% end %>

    <script type="text/javascript">
        latestResponsesToggle();
        readCronExpression();
        $('form').each(function (i, e) {
            $(e).find('.cron_exp_field:last').trigger('input')
        })
    </script>
  </div>
</div>

app/views/pokes/create.js.erb
$('.flash_notice_container').replaceWith('<%=j(render(partial: 'tool_components/flash_notice')) %>');
window.location.reload();

app/views/pokes/destroy.js.erb
$('.flash_notice_container').replaceWith('<%=j(render(partial: 'tool_components/flash_notice')) %>');
<% if @poke.destroyed? %>
$('.poke_form_<%= @poke.id %>').remove();
<% end %>
latestResponsesToggle();

app/views/pokes/index.html.erb
<% if @team %>
  <%= render(partial: 'teams/tab_structure', locals: {partial_to_render: 'pokes/pokes_tab_content'}) %>
<% else %>
  <%= render(partial: 'pokes/pokes_tab_content') %>
<% end %>

app/views/pokes/update.js.erb
$('.flash_notice_container').replaceWith('<%=j(render(partial: 'tool_components/flash_notice')) %>');
$('.poke_form_<%= @poke.id %>').replaceWith('<%=j(render(partial: 'pokes/card', locals: {poke: @poke})) %>');
latestResponsesToggle();